# Generated by Django 4.1.3 on 2022-11-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="total_time",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
