# Generated by Django 4.1.3 on 2022-11-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_alter_certificate_total_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="institution",
            field=models.CharField(max_length=65),
        ),
    ]
